__title__ = 'pyntegrate'
__description__ = 'Pyntegrate is an example of various sorting algorithms using C Extensions.'
__url__ = 'https://github.com/rtsfred3/pyntegrate'
__version__ = '1.3.4b1'
__author__ = 'Ryan Fredrickson'
__author_email__ = 'rtsfred3@gmail.com'
__license__ = 'Apache 2.0'
