name: Run Unit Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        strategy:
            matrix:
                python-version: [ '3.7', '3.8', '3.9', '3.10' ]
                platform: [ ubuntu-latest, macos-latest, windows-latest ]
        
        runs-on: ${{ matrix.platform }}
        
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    python3 setup.py install
            - name: Running Unit Tests
              run: cd tests/ && python3 -m unittest test_integrate.py
