name: Run Unit Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        # if: false
        strategy:
            matrix:
                python-version: [ '3.11', '3.12' ]
                # platform: [ ubuntu-latest ]

                setting:
                    - platform: 'macos-latest'
                      args: '--target universal-apple-darwin'
                    - platform: 'ubuntu-22.04'
                      args: ''

                # platform: [ ubuntu-latest, macos-latest ]
                # platform: [ubuntu-latest, macos-latest, windows-latest]
        
        runs-on: ${{ matrix.setting.platform }}
        
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Updating pip
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            - name: Installing pyntegrate
              run: |
                python -m pip install -e .
                python3 -m build
                # python3 setup.py install
            - name: Running Unit Tests
              run: cd tests/ && python -m unittest test_integrate.py
    
    win-test:
        if: false
        strategy:
            matrix:
                python-version: [ '3.9', '3.10', '3.10', '3.11', '3.12' ]
                platform: [ windows-latest ]
    
        runs-on: ${{ matrix.platform }}
    
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Updating pip
              run: python -m pip install --upgrade pip
            - name: Install dependencies
              run: pip install pytest
            - name: Installing pyntegrate
              run: python3 setup.py install
            - name: Running Unit Tests
              run: cd tests && pytest test_integrate.py
