---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    strategy:
      matrix:
        python-version: [ '3.7' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          ref: 'pypi'
          python-version: ${{ matrix.python-version }}
      - name: Get Version Number
        id: version
        run: echo "::set-output name=version::$(python3 setup.py --version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install wheel
      - name: Build package
        run: python3 setup.py sdist && python3 setup.py bdist_wheel
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev_latest"
          prerelease: true
          title: "Latest Dev Build"
          files: |
            dist/*.whl
            dist/*.tar.gz
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev_v${{ steps.version.outputs.version }}"
          prerelease: true
          title: "Dev Build v${{ steps.version.outputs.version }}"
          files: |
            dist/*.whl
            dist/*.tar.gz
