---
name: "pre-release"

on:
    push:
        branches:
            - "pypi-staging"

jobs:
    gen-pre-release:
        name: "Generating Wheel Files for GitHub Pre-Release"
        runs-on: "ubuntu-latest"
    
        strategy:
            matrix:
                python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Get Version Number
              id: version
              run: echo "::set-output name=version::$(python3 setup.py --version)"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install build
                pip install wheel
            - name: Build package
              run: ./generate_whl.sh && python3 setup.py bdist_wheel --plat-name=win32 && python3 setup.py bdist_wheel --plat-name=win-amd64
            - name: Uploading Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: pre-whl-artifacts
                  path: |
                        dist/*.whl
                        dist/*.tar.gz
    
    pre-release:
        name: "Pre-Release on GitHub"
        runs-on: "ubuntu-latest"
        needs: gen-pre-release
        
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7
            - name: Get Version Number
              id: version
              run: echo "::set-output name=version::$(python3 setup.py --version)"
            - name: Downloading Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: pre-whl-artifacts
                  path: dist/
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "dev_latest"
                  prerelease: true
                  title: "Latest Dev Build"
                  files: |
                        dist/*.whl
                        dist/*.tar.gz
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "dev_v${{ steps.version.outputs.version }}"
                  prerelease: true
                  title: "v${{ steps.version.outputs.version }}"
                  files: |
                        dist/*.whl
                        dist/*.tar.gz
